site_name: Verifiable Trade Documents
site_url: https://uncefact.github.io/spec-unvtd/
theme: 
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  features: 
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode
      primary: white
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: grey
copyright: 
  UN/CEFACT 2024
plugins:
  - include-markdown
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/react/17.0.2/umd/react.production.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/react-dom/17.0.2/umd/react-dom.production.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/ajv/8.12.0/ajv.min.js
  - https://unpkg.com/@rjsf/core/dist/react-jsonschema-form.umd.min.js
